version = 0.1
[default.deploy.parameters]
stack_name = "go-lambda-dynamodb"
resolve_s3 = true
s3_prefix = "go-lambda-dynamodb"
region = "ca-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
image_repositories = []
